# Generated by Django 4.2.6 on 2024-03-10 10:34

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
            ],
        ),
        migrations.CreateModel(
            name="Cast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                ("subject", models.CharField(max_length=255, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
            ],
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedbackSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_taken", models.DurationField(verbose_name="Time Taken")),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "guesses",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "imdb_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="IMDB ID"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(default=0, verbose_name="Year of Release"),
                ),
                (
                    "cast",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None, to="movie.cast", verbose_name="Cast"
                    ),
                ),
                (
                    "directors",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None, to="movie.director", verbose_name="Directors"
                    ),
                ),
                (
                    "genres",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None, to="movie.genre", verbose_name="Genres"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="User ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Writer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.archive"
                    ),
                ),
                (
                    "guessed_movies",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None,
                        sort_value_field_name="order",
                        through="movie.Guess",
                        to="movie.movie",
                        verbose_name="Guessed Movies",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.user"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user activities",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="music_directors",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, to="movie.musicdirector", verbose_name="Music Directors"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_houses",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None,
                to="movie.productionhouse",
                verbose_name="Production Houses",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="writers",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, to="movie.writer", verbose_name="Writers"
            ),
        ),
        migrations.AddField(
            model_name="guess",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
            ),
        ),
        migrations.AddField(
            model_name="guess",
            name="user_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie.useractivity"
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "subjects",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None,
                        to="movie.feedbacksubject",
                        verbose_name="Subjects",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="archive",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.movie",
                verbose_name="Movie",
            ),
        ),
    ]
