# Generated by Django 4.2.6 on 2023-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "subjects",
                    models.ManyToManyField(
                        to="movie.feedbacksubject", verbose_name="Subjects"
                    ),
                ),
            ],
        ),
    ]
