# Generated by Django 4.2.6 on 2023-11-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0004_feedbacksubject_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="production_house",
        ),
        migrations.AddField(
            model_name="movie",
            name="directors",
            field=models.ManyToManyField(to="movie.director", verbose_name="Directors"),
        ),
        migrations.AddField(
            model_name="movie",
            name="production_houses",
            field=models.ManyToManyField(
                to="movie.productionhouse", verbose_name="Production Houses"
            ),
        ),
    ]
