# Generated by Django 4.2.6 on 2023-12-13 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0005_remove_movie_director_remove_movie_production_house_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_taken", models.DurationField(verbose_name="Time Taken")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.movie"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "guesses",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="User ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "guessed_movies",
                    models.ManyToManyField(
                        through="movie.Guess",
                        to="movie.movie",
                        verbose_name="Guessed Movies",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movie.user"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "user activities",
            },
        ),
        migrations.AddField(
            model_name="guess",
            name="user_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movie.useractivity"
            ),
        ),
    ]
